### ISSUE TITLE
let's translate easier

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [noahjutz/Splitfit#34]
let's translate on weblate - it's easier than on github 

https://weblate.bubu1.eu/

**Comment by noahjutz** [comment]
Thanks for the submission. Currently, only about a third of the strings in the app are string resources, but I suppose we can start translating those already.

I've never done any crowdsourced translation, could you help me out with these questions?
* Why did you chose weblate?
* What's up with the subdomain you linked to? Is it an instance of the webservice running on bubu1.eu?

**Comment by mondlicht-und-sterne** [comment]
* I chose weblate because it is open source,.
* Yes, it is an instance of the web service, the bubu1.the eu is running. this is the instance of the F-Droid maintainer "bubu" - I'm sure you've already read it somewhere. on its instance, after you have entered your project and its strings, you can start or start translating immediately..

* now something about me: i translated fdroid apps for at least 5 hours every day 7 days a week from october 2018 to december 2020. 
* I paint the logos as acrylic paintings and promote them on mastodon and pixelfed. some of them even make it into an exhibition.

**Comment by fossdd** [comment]
Translating on Weblate makes realy sense. Weblate is for begginers a great platform for translating stuff apps they use every day.

The difference for "creating fork, search for the strings file, copieng if language not exist, editing xml, opening pr, wait for reviewing, etc" and "simply translate over a FLOSS web app (also anonymous)" is big.

You can simply if you wait for the bus and have some minutes, translate some strings, easy!

Maybe helps https://docs.weblate.org/en/latest/devel/integration.html to set up weblate.

**Comment by noahjutz** [comment]
Thank you both. I'll look into setting up weblate for my project.

**Comment by mondlicht-und-sterne** [comment]
https://weblate.bubu1.eu/projects/splitfit/

thank you very much. I have already started translating.

**Comment by fossdd** [comment]
Yeah, nice and I have finished the German translation. @noahjutz You can also add badges of weblate: https://weblate.bubu1.eu/widgets/splitfit/

<a href="https://weblate.bubu1.eu/engage/splitfit/">
<img src="https://weblate.bubu1.eu/widgets/splitfit/-/svg-badge.svg" alt="Translation status" />
</a>

**Comment by mondlicht-und-sterne** [comment]
@fossdd thanks we are a good team

**Comment by noahjutz** [comment]
Thank you for translating! I'm going to add the badge soon. 

I haven't been able to figure out how to push the translation into my repo. I got an alert saying "your push URL seems to miss credentials" (for https://github.com/noahjutz/Splitfit). I'm going to use SSH and see if that works.

**Comment by noahjutz** [comment]
I can't find an option to add ssh keys to weblate. I got following error upon not specifying a key:
```
no such identity: /var/lib/weblate/data/ssh/id_rsa: No such file or director
```

Is it possible to `scp` a keypair to `/var/lib/weblate/data/ssh/id_rsa`? Do I need the weblate client?

I tried to use the weblate github application to authenticate as well, but it didn't fix the error `fatal: could not read Username for 'https://github.com': terminal prompts disabled
 (128)`. I couldn't find any documentation on the github app.

**Comment by fossdd** [comment]
Did you sepcified the https git clone url? A ssh key is only used for ssh git urls

6 Feb 2021, 20:36 by notifications@github.com:

**Comment by noahjutz** [comment]
I tried https initially, but that threw an error saying "your push URL seems to miss credentials", so I tried ssh later, too. If you could help me get the https method working, that would be great.

I simply set `https://github.com/noahjutz/Splitfit.git` as the push url in the weblate settings.

**Comment by fossdd** [comment]
Okay, maybe dry `git@github.com:noahjutz/Splitfit.git` 

6 Feb 2021, 22:10 by notifications@github.com:

**Comment by noahjutz** [comment]
I already tried that. It threw
```
no such identity: /var/lib/weblate/data/ssh/id_rsa: No such file or directory
```

**Comment by fossdd** [comment]
Okay, i reproduced that. And i fixed that using `https://<USERNAME>:<MY GITHUB TOKEN>@github.com/<USERNAME>/<PROJECT>.git` as source code repo and as push url.
You have to setup a github access token: https://github.com/settings/tokens (I gived ful `repo` access).
That seems to success.

**Comment by noahjutz** [comment]
alright, I'll try that. Thank you for helping me out.

**Comment by noahjutz** [comment]
It worked! Thanks a lot.

**Comment by mondlicht-und-sterne** [comment]
@noahjutz https://weblate.bubu1.eu/projects/splitfit/strings-xml/ 

it grows ;)

**Comment by mondlicht-und-sterne** [comment]
https://weblate.bubu1.eu/engage/splitfit/

actually 13 languages. i think its an good start.

@noahjutz

**Comment by noahjutz** [comment]
Thank you for your hard work! I'm impressed; do you really know all these languages?

Anyways, I looked through the german translation, and while I'm mostly pleased, I'll have to replace some of the translations (for instance, "weight" was translated to "Vertreter". But that can always be improved later on.

I intend add a "contributors" section in the about page at some point and credit you for your translations.

---

- [x] Weblate is set up
- [x] Successfully pushes to branch and can be merged
- [x] Badge is in README 

I'll close this issue as weblate translations are now set up.
