### ISSUE TITLE
Database path

### ISSUE THREAD

**Issue by mbnoimi** [noahjutz/Splitfit#37]
Hi,

I'm working on filling this [workout plan](https://www.buffdudes.us/blogs/fitness/88178823-12-week-plan-original-edition), but I couldn't figure out where Splitfit stores its files.

May you please tell me where can I find the config files to be able to share my workout plan?

PS. I've a ton of the suggestions, so I'll post them one by one. Furthermore, I'll post them depending on my personal experience because there are critical fixings/feature  requests. I wish to find some time to response to them.
Unfortunately I haven't any knowledge in Kotlin, so PR is impossible to me.

**Comment by noahjutz** [comment]
There are no config files, I'm not sure what exactly you're referring to. Routines are stored in the database, which can be exported from the settings.

Because all data is overriden on import, "sharing" routines across users is currently not possible.

**Comment by mbnoimi** [comment]
> Routines are stored in the database

What's the path of the database?

**Comment by mbnoimi** [comment]
BTW, what's the benefit of `workout_table` ? I see it completely empty!

**Comment by noahjutz** [comment]
The database is stored in the internal app storage. The full path is `/data/data/com.noahjutz.splitfit.fdroid/databases/workout_routines_database`.

I'm closing this as it's not an issue with the app, but you can feel free to ask further questions.
