### ISSUE TITLE
Exercises multi-lines

### ISSUE THREAD

**Issue by mbnoimi** [noahjutz/Splitfit#44]
I suggest enabling muli-lines for exercise's title (I forced to modify sqlite database manually to be able to add multi-lines)

![_20210211_185737](https://user-images.githubusercontent.com/284547/107664040-13a24900-6c9d-11eb-8686-1267469b65e4.png)
![_20210211_185807](https://user-images.githubusercontent.com/284547/107664044-14d37600-6c9d-11eb-92ce-5d4b270b1e2d.png)

**Comment by noahjutz** [comment]
I dont think I want to implement this. The reason you want it seems to be supersets, but I want to implement supersets in a different way that doesn't include creating a seperate exercise.

**Comment by mbnoimi** [comment]
> I dont think I want to implement this. The reason you want it seems to be supersets, but I want to implement supersets in a different way that doesn't include creating a seperate exercise.

This is much better. Thanks

**Comment by mbnoimi** [comment]
> but I want to implement supersets in a different way that doesn't include creating a seperate exercise.

I suggest reopening this issue until you implement the feature you've talked about.

**Comment by noahjutz** [comment]
@mbnoimi I've opened a new issue #58
