### ISSUE TITLE
Exercise note

### ISSUE THREAD

**Issue by mbnoimi** [noahjutz/Splitfit#46]
I suggest adding a field for notes in the exercise's activity because in some cases it's vital to add a note explains important info about the exercise.

For example `deps` needs some explanation.
![image](https://user-images.githubusercontent.com/284547/107665244-4f89de00-6c9e-11eb-95a5-d2d7c0f3c521.png)

**Comment by noahjutz** [comment]
Added in 921a2c44, 8852a1a9, 940ba99a, 02423558, 55632ba6 for v0.1.0-beta01. I hope it meets your needs.
