### ISSUE TITLE
Export/Import program

### ISSUE THREAD

**Issue by mbnoimi** [noahjutz/Splitfit#52]
In case you approve to add feature request #51 
I suggest adding an option for Export/Import a specific program with all related exercises (without workouts table) in addition to Backup/Restore the whole app's database.

EDIT: This feature allows the users to share programs easily (in the attachment you can see my start point for inputting `Buff Dudes 12 Week Home Program`)
[splitfit-backup-202102111838.sqlite3.zip](https://github.com/noahjutz/Splitfit/files/5977396/splitfit-backup-202102111838.sqlite3.zip)

**Comment by noahjutz** [comment]
I'm not sure about programs yet, but exporting/importing partial data seems like a good idea either way. I'm going to open a more broad issue and close this one if that's fine by you.

**Comment by mbnoimi** [comment]
No problem.
