### ISSUE TITLE
"Start Workout" button in Routine Editor

### ISSUE THREAD

**Issue by mbnoimi** [noahjutz/Splitfit#53]
I suggest adding a big start button in routing details 
![_20210214_131654](https://user-images.githubusercontent.com/284547/107873945-29935200-6ec7-11eb-8523-f0a025bfb325.png)

And in routing list (beside delete button)

https://user-images.githubusercontent.com/284547/107873950-33b55080-6ec7-11eb-8959-0bdacde5d28e.mp4

**Comment by noahjutz** [comment]
I don't want to add multiple FABs in order to comply with material design guidelines. Maybe I'll replace the current one with "start workout" and move "add exercise" to a button at the bottom of the list.

**Comment by mbnoimi** [comment]
You can use multiple FABs as following:
![external-content duckduckgo com](https://user-images.githubusercontent.com/284547/108303860-cac82400-71b7-11eb-9073-81d14e021dbe.gif)

**Comment by noahjutz** [comment]
yes, multiple FABs need to be related actions though. I'll still think about it, but at the moment, I think my idea is best for UX.

**Comment by noahjutz** [comment]
Here's my implementation. Feel free to reopen this issue if you're unhappy with this solution.
![image](https://user-images.githubusercontent.com/30440621/117552485-e2db7100-b04b-11eb-98bf-423da31e9ba3.png)
