### ISSUE TITLE
APK releasing

### ISSUE THREAD

**Issue by mbnoimi** [noahjutz/Splitfit#56]
I know Splitfit is still under in alpha release, but I prefer to get the recent APK as soon as you create a new tag.

May you please publish APK along with creating a new tag/release.

**Comment by noahjutz** [comment]
Seamlessly updating with F-droid requires issue #39 to be fixed. #38 is related, too.

In the mean time, I can attach an unsigned debug build if you want.

**Comment by mbnoimi** [comment]
> I can attach an unsigned debug build if you want.

No problem. Thank you in advance

**Comment by noahjutz** [comment]
I added the debug apk.
