### ISSUE TITLE
app translation

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [noahjutz/Splitfit#66]
hi when i just installed v0.1.0-alpha9, i saw that there should be new strings that need to be translated. and also on the "about" page. and also in training plans and exercises. 
but the app is improving, thanks for programming.

**Comment by noahjutz** [comment]
Yes, I still have to create a lot of string resources. That'll come slowly with upcoming releases. Thanks for the feedback.

**Comment by mondlicht-und-sterne** [comment]
@noahjutz Yes, of course. I always see if I can translate something.

**Comment by mondlicht-und-sterne** [comment]
@noahjutz i cant translate. if i translate and go to the next i see the notice "Insufficient rights to save translations." :-/

**Comment by noahjutz** [comment]
Thanks for the info. I recently changed a setting in weblate so users can't make direct translations, but only vote for suggestions. I want to keep it like this in the long run in order to improve translation quality. Can you still suggest translations or is it not possible at all?

**Comment by mondlicht-und-sterne** [comment]
translation is no longer possible

**Comment by noahjutz** [comment]
I can see that fossdd has successfully added a suggestion for [new_exercise](https://weblate.bubu1.eu/translate/splitfit/strings-xml/de/?checksum=5fcc85ba5cb1860#suggestions), so it must be a problem on your end. 

Are you sure you're using the suggest button?
![Screenshot from 2021-03-13 13-14-25](https://user-images.githubusercontent.com/30440621/111029651-127c4d00-83fe-11eb-8941-5e0f2f00cf4c.png)

**Comment by fossdd** [comment]
I have used the `Suggest` button. But why can't we `Save` things?

**Comment by noahjutz** [comment]
Giving everyone the permission to save translations directly will lead to some incorrect translations. Suggested translations always have to be reviewed by two other translators, which results in better translations.

**Comment by mondlicht-und-sterne** [comment]
However, if you don't see any results, you lose the desire to continue translating the project.

So you could concentrate on programming and let the others program.

**Comment by noahjutz** [comment]
I'm grateful to all translators, most notably you @mondlicht-und-sterne - thank you. However, I'm not going to sacrifice app quality in order to drive your motivation. I'm sorry but I have to double down on my opinion here.

Your contribution isn't any less valuable or appreciated because of this change. It might take longer for your translations to be incorporated into the app, but this is a necessary measure to improve translations.

**Comment by mondlicht-und-sterne** [comment]
then let others talk to the wall now.

**Comment by noahjutz** [comment]
I'm sorry, I'm not sure I understand what you're saying. Are you saying I'm not listening to contributors like yourself enough? I'm sorry I made you feel that way. I'm always open to new suggestions, but as the project maintainer I have to make decisions that might leave some unsatisfied. I made the decision to prohibit direct translations to benefit everyone using Splitfit in other languages.

I'm always happy to reevaluate my decisions, and if you can give me a compelling reason to reinstate direct translations, I will think about it again.

I hope I can still count on you to continue translating the project. Regardless, I want express my gratitude your contributions so far.

**Comment by mondlicht-und-sterne** [comment]
Will there be another opportunity to translate later (whenever)? That was not possible for a long time.

**Comment by noahjutz** [comment]
yes, I'm sorry, it's just very time consuming to maintain weblate. I'm currently busy with other aspects of the app, so it will take a while before translation is possible again.
