### ISSUE TITLE
setting to hide bottom navigation labels

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [noahjutz/Splitfit#76]
Version tested: Splitfit v0.1.0-alpha13

Training plans, exercises, insights and settings are currently displayed - as well as their logos/icons. 
My idea would be to enter in the settings: this view /and/ the view with only the 4 logos (without the description).

**Comment by noahjutz** [comment]
Thanks for the suggestion.

**Comment by noahjutz** [comment]
Here's how it looks:

![Screenshot_20210425-201840_Splitfit](https://user-images.githubusercontent.com/30440621/116004565-916ec300-a603-11eb-9ef1-ec68dea659e2.png)
