### ISSUE TITLE
Restore Database Doesn't Show .db Files

### ISSUE THREAD

**Issue by georgepestell** [noahjutz/Splitfit#77]
- [x] I have read the [contribution guidelines](https://github.com/noahjutz/Splitfit/blob/master/CONTRIBUTING.md).
- [x] I am using the [latest version](https://github.com/noahjutz/Splitfit/releases).

**Describe the bug**
When restoring the database, .db files are not displayed. However, renaming the file to a .txt, or other generic media file type allows the file to be restored.

**To Reproduce**
1. Backup database to file system
2. Click on Restore in settings
4. The backup will not be displayed

**Expected behavior**
I would expect the .db file to be shown in the restore file picker window. Or for a file association with the .db files to be able to be opened with splitfit.

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - Android version: 11 (5th April 2021)

**Comment by noahjutz** [comment]
Thanks for the bug report. I was able to reproduce it and I'll start working on fixing it.

**Comment by noahjutz** [comment]
The issue lies in this line of code:
https://github.com/noahjutz/Splitfit/blob/d4d6ef15a96a6b71ba8ae46b16fef3b1df6b58ee/app/src/main/java/com/noahjutz/splitfit/ui/settings/AppSettings.kt#L61-L67

`ActivityResultContracts.OpenDocument()` seems to only accept certain files.  

Overriding the class like this doesn't fix the bug.
```kt
object : ActivityResultContracts.OpenDocument() {
  override fun createIntent(context: Context, input: Array<out String>): Intent {
    return super.createIntent(context, arrayOf("*/*"))
  }
}
```

I haven't found a fix yet.

**Comment by mbnoimi** [comment]
I've a similar bug, so I recorded a screencast and compared Splitfit (0.1.0-alpha14) with [FitoTrack](https://github.com/russok/FitoTrack). I believe this issue related to file chooser parameters.

IMPORTANT: This bug doesn't occur in Android 10 and above while it occurs in Android 8.1

![Screenshot_20210505-063447](https://user-images.githubusercontent.com/284547/117094661-09a85780-ad6d-11eb-89d9-551075766bdc.png)

https://user-images.githubusercontent.com/284547/117094741-41170400-ad6d-11eb-9267-e5df98742b51.mp4

**Comment by noahjutz** [comment]
Thanks for the info, @mbnoimi

**Comment by mbnoimi** [comment]
@noahjutz May you please find some time to fix this bug?
I'm no longer able to restore my db when I moved to a new mobile phone.

**Comment by noahjutz** [comment]
@

**Comment by noahjutz** [comment]
Hi, I'm working on it. In the mean time, please change the backup file extension from .db to .txt as a workaround. You can then import the .txt file.

**Comment by mbnoimi** [comment]
> change the backup file extension from .db to .txt as a workaround. You can then import the .txt file.

It doesn't work. The file chooser doesn't display storage media at all (as shown below)



https://user-images.githubusercontent.com/284547/117583900-66f82c00-b112-11eb-9fed-ecdfadc24cc2.mp4

**Comment by noahjutz** [comment]
Can you try changing it to .png? Sorry for the inconvenience.

**Comment by mbnoimi** [comment]
> Can you try changing it to .png?

hehehhe, it works... what a silly fix

**Comment by mbnoimi** [comment]
This bug doesn't occur in Backup process (I'm able to select media storage without any problem)
![image](https://user-images.githubusercontent.com/284547/117614450-01875800-b171-11eb-935d-82094585ba32.png)
